# Generated by Django 3.1 on 2020-08-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.CharField(max_length=30, verbose_name='user vk id')),
                ('action', models.CharField(default='main', max_length=30, verbose_name='current action')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='task description')),
                ('deadline_date', models.DateField(default=0, verbose_name='date of deadline')),
                ('deadline_time', models.TimeField(default=0, verbose_name='time of deadline')),
                ('finished', models.BooleanField(default=False, verbose_name='is task finished')),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.user', verbose_name='user')),
            ],
        ),
    ]
